# Copyright © SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "winit"
version = "0.3.3"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
build = "build.rs"
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"
publish = false

[[bin]]
path = "main.rs"
name = "winit"

[dependencies]
slint = { path = "../../api/rs/slint", default-features = false, features = ["compat-0-3-0", "std"] }
winit = { version = "0.27.5", default-features = false, features = ["x11", "wayland"] }
i-slint-core = { path = "../../internal/core", default-features = false }
i-slint-renderer-skia = { path = "../../internal/renderers/skia" }

[build-dependencies]
slint-build = { path = "../../api/rs/build" }

